name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push FastAPI Trivial
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./methods/fastapi-trivial/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-trivial:latest
      - name: Build and push FastAPI Optimum ONNX
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./methods/fastapi-optimum-onnx/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-optimum-onnx:latest
      - name: Checkout code
        uses: actions/checkout@v2
